info.app:
  name: @project.name@
  description: @project.description@
  version: v@project.version@

server:
  servlet.context-path: /api/v1
  port: 8080

spring:
  application.name: Spacecrafts
  datasource:
    url: jdbc:h2:mem:sc_db
    username: guest
    password: changeIt
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2.console:
    path: /h2-console
    enabled: true
    settings.trace: false
    settings.web-allow-others: true
  cache:
    cache-names: allShips

openapi.swaggerW2MTravelOpenAPI30.base-path: /
jakarta.validation.constraints.Min.message: El valor debe ser mayor a 1

springdoc:
  packagesToScan:
    - travel.w2m.techproof.web
    - travel.w2m.techproof.model
    - travel.w2m.techproof.controller
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    use-root-path: true
  cache:
    disabled: true

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    travel.w2m.techproof: INFO
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%5level){faint} %clr(---){faint} %-40.40clr(%logger{0}.%M){blue} %clr(:){red} %clr(%msg){faint}%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"